# Generated by Django 4.1.1 on 2022-09-21 04:05

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("client", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="client",
            name="date_joined",
            field=models.DateField(
                default=datetime.datetime(
                    2022, 9, 21, 4, 5, 51, 192397, tzinfo=datetime.timezone.utc
                )
            ),
        ),
    ]
