# Generated by Django 4.1.1 on 2022-09-21 12:56

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("product", "0002_alter_product_date_added"),
    ]

    operations = [
        migrations.CreateModel(
            name="Order",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("quantity", models.IntegerField(default=1)),
                (
                    "payment_method",
                    models.CharField(
                        choices=[
                            ("CARD", "DEBIT CARD"),
                            ("PYPL", "PAYPAL"),
                            ("STRP", "STRIPE"),
                        ],
                        default="CARD",
                        max_length=10,
                    ),
                ),
                (
                    "placed_on",
                    models.DateTimeField(
                        default=datetime.datetime(
                            2022,
                            9,
                            21,
                            12,
                            56,
                            50,
                            933994,
                            tzinfo=datetime.timezone.utc,
                        )
                    ),
                ),
                (
                    "client",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="product.product",
                    ),
                ),
            ],
            options={
                "ordering": ["placed_on"],
            },
        ),
        migrations.AddConstraint(
            model_name="order",
            constraint=models.UniqueConstraint(
                fields=("client", "product", "placed_on"), name="duplicate_order"
            ),
        ),
    ]
