# Generated by Django 4.1.1 on 2022-09-21 04:29

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("order", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="payment_method",
            field=models.CharField(
                choices=[
                    ("CARD", "DEBIT CARD"),
                    ("PYPL", "PAYPAL"),
                    ("STRP", "STRIPE"),
                ],
                default="CARD",
                max_length=10,
            ),
        ),
        migrations.AddField(
            model_name="order",
            name="placed_on",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2022, 9, 21, 4, 29, 22, 776296, tzinfo=datetime.timezone.utc
                )
            ),
        ),
    ]
