# Generated by Django 4.1.1 on 2022-09-21 12:56

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True, null=True)),
                ("price", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "image",
                    models.ImageField(blank=True, null=True, upload_to="products/"),
                ),
                (
                    "date_added",
                    models.DateTimeField(
                        default=datetime.datetime(
                            2022,
                            9,
                            21,
                            12,
                            56,
                            43,
                            158430,
                            tzinfo=datetime.timezone.utc,
                        )
                    ),
                ),
                ("slug", models.SlugField()),
                ("available_qty", models.IntegerField()),
            ],
        ),
        migrations.AddConstraint(
            model_name="product",
            constraint=models.UniqueConstraint(
                fields=("name", "description"), name="duplicate_product"
            ),
        ),
    ]
