# Generated by Django 4.1.1 on 2022-09-21 12:56

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("product", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="date_added",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2022, 9, 21, 12, 56, 50, 933349, tzinfo=datetime.timezone.utc
                )
            ),
        ),
    ]
