# Generated by Django 4.1.1 on 2022-09-21 04:29

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("product", "0002_alter_product_date_added_alter_product_price"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="date_added",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2022, 9, 21, 4, 29, 22, 775192, tzinfo=datetime.timezone.utc
                )
            ),
        ),
    ]
